name: New feature checker

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize # push
    path:
      - source/refined-github.ts

jobs:
  check:
    outputs:
      name: ${{ steps.name.outputs.first_match }}
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, 'Add') && endsWith(github.event.pull_request.title, 'feature')
    steps:
      - name: Find feature name
        id: name
        uses: AsasInnab/regex-action@v1
        with:
          regex_pattern: '(?<=Add `)\w+(?=` feature)'
          regex_flags: g
          search_string: ${{ github.event.pull_request.title }}

  feature-file:
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.outputs.name
    steps:
      - uses: actions/checkout@v2
      - name: Has ${{ needs.check.outputs.name }}.tsx been created?
        uses: mudlabs/simple-diff@v1.2.0
        with:
          path: source/features/${{ needs.check.outputs.name }}.tsx

  content-script:
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.outputs.name
    steps:
      - uses: actions/checkout@v2
      - name: Has `${{ needs.check.outputs.name }}` been imported
        run: grep "import './features/${{ needs.check.outputs.name }}';" source/refined-github.ts -q

  readme:
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.outputs.name
    steps:
      - uses: actions/checkout@v2
      - name: Has `${{ needs.check.outputs.name }}` been documented
        run: grep '"${{ needs.check.outputs.name }}"' readme.md -q
